add icon extraction
yoyrandao/ows pull request #1
Opened 2022-09-01 00:05 UTC by xxpopygaixx

feat: icon extraction
feat: initial proc selection

2022-09-01 07:24 UTC, yoyrandao requested changes
lgtm, но есть комменты

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/LowLevel/Interop.cs
>  	[DllImport("user32.dll", SetLastError = true)]
Удали тогда это, раз оно не нужно
Я думал, когда добавлял, что он даст фокус на окно, но чет видимо твой метод работает, а этот нет

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/LowLevel/Interop.cs
> +	[DllImport("user32.dll")]
Предлагаю ```SetLastError``` везде выставлять в ```true```

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/MainWindow.xaml.cs
> +    private void TextBoxBase_OnTextChanged(object sender, TextChangedEventArgs e)
Тоже удалить

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +				source = Icon.ExtractAssociatedIcon(activeWindow.MainModule?.FileName).ToImageSource();
Я вот думаю, возможна ли тут ситуация, когда иконки у приложения нет, но оно в альттабе
Кажется все таки может, поэтому думаю стоит подумать о фолбеке

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +				Trace.WriteLine(string.Format("Unable to locate executable for proc with Pid [{0}] and Tittle [{1}]",
Typo
```suggestion
				Trace.WriteLine(string.Format("Unable to locate executable for proc with Pid [{0}] and Title [{1}]",
```

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +			if (source != null && source.CanFreeze)
```suggestion
			if (source is { CanFreeze: true })
```

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +            };
Переключи IDE на табы пж

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Dto/ActiveWindow.cs
> +	public ImageSource? ImageSource { get; set; }
```init```

2022-09-01 07:24 UTC, yoyrandao commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +				Trace.WriteLine(string.Format("Unable to extract icon for file [{0}] and Tittle [{1}]", executablePath));
тут Typo + второго параметра для интерполяции нет

2022-09-01 20:35 UTC, xxpopygaixx commented on src/ows-gui/Providers/ActiveWindowsProvider.cs
> +				source = Icon.ExtractAssociatedIcon(activeWindow.MainModule?.FileName).ToImageSource();
Иконка нужна исключительно для view, пусть она и разбирается что с ней делать

2022-09-03 06:18 UTC, yoyrandao approved these changes
lgtm

2022-09-03 06:19 UTC, merged